name: Docker

on:
  pull_request:
    branches-ignore: ['beta*', 'dev*', 'next*']
  push:
    branches-ignore: ['beta*', 'dev*', 'next*']
    tags: ['nightly*', 'v*.*.*']
  release:
    types: [published]
  schedule:
    - cron: '30 9 * * *' # 9:30am UTC
  workflow_dispatch:

env:
  BASENAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        env:
          PUBLIC_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        with:
          buildargs: PUBLIC_FIREBASE_CONFIG,PUBLIC_GOOGLE_MAPS_API_KEY
          dockerfile: Dockerfile
          name: ${{ env.BASENAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          snapshot: true
          tags: latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
