name: Firebase

concurrency:
  group: "firebase"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  CHANNEL: live
  FIREBASE_PID: svkcl-d7eb1
  RUST_BACKTRACE: full


on:
  push:
    branches: [ main ]
    tags: [ v*.*.* ]
  release:
    types: [ published ]
  repository_dispatch:
    types: [ firebase-deploy ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write

jobs:
  publisher:
    environment:
      name: production
      url: https://${{ env.FIREBASE_PID }}.firebaseapp.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          npm install
          npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          channelId: ${{ env.CHANNEL }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVKCL_D7EB1 }}
          projectId: ${{ env.FIREBASE_PID }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
