name: Firebase

concurrency:
  group: 'firebase'
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always
  CHANNEL: live
  FIREBASE_PID: svkcl-d7eb1
  NODE_VERSION: 18

on:
  push:
    branches: [main]
    tags: [v*.*.*]
  release:
    types: [published]
  repository_dispatch:
    types: [firebase-deploy]
  workflow_dispatch:

permissions: write-all

jobs:
  publisher:
    env:
      PUBLIC_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    environment:
      name: production
      url: https://${{ env.FIREBASE_PID }}.firebaseapp.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: npm install && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        with:
          channelId: ${{ env.CHANNEL }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SVKCL_D7EB1 }}
          projectId: ${{ env.FIREBASE_PID }}
          repoToken: ${{ secrets.GITHUB_TOKEN }}
