name: 'Nightly Build'

on:
  # schedule:
  #   - cron: '00 06 * * 1-5' # Run every Monday-Friday at 6:00 UTC (6:00 am UTC)
  workflow_dispatch:

jobs:
  create-nightly-hash:
    runs-on: ubuntu-latest
    outputs:
      nightly-hash: ${{ steps.create-nightly-hash.outputs.NIGHTLY_HASH }}
    steps:
      - uses: actions/checkout@v3
      # A 1 is required before the timestamp
      # as lerna will fail when there is a leading 0
      # See https://github.com/lerna/lerna/issues/2840
      - name: Install Dependencies
        run: npm ci --no-package-lock
        shell: bash
      - id: create-nightly-hash
        name: Create Nightly Hash
        # The date should output YYYYMMDD
        # so that it is human readable
        run: |
          echo "NIGHTLY_HASH=$(node ./.scripts/bump-version.js)-nightly.$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        shell: bash

  finalize-release:
    needs: [create-nightly-hash, release-ionic]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # We need to push the commit changes in order for the tags
    # to get updated, but we don't need to keep the changelog
    # changes around.
    - name: Delete Nightly Branch
      run: |
        git checkout main
        git branch -D tmp-${{ needs.create-nightly-hash.outputs.nightly-hash }}
        git push origin --delete tmp-${{ needs.create-nightly-hash.outputs.nightly-hash }}
      shell: bash