name: Node

env:
  NODE_VERSION: 18
  PUBLISH: ${{ github.event.inputs.publish }}

on:
  pull_request:
    branches-ignore: [beta*, dev*, next*, nightly*]
  push:
    branches-ignore: [beta*, dev*, next*, nightly*]
    tags: [v*.*.*]
  release:
  repository_dispatch:
    types: [node]
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Node version'
        required: true
        default: '18.x'
      publish:
        description: 'Publish to npm'
        required: false
        default: 'false'

jobs:
  build:
    env:
      PUBLIC_FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
      PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            master-${{ runner.os }}-node-${{ env.NODE_VERSION }}
